export const ADD_EXPENSE = 'ADD_EXPENSE';
export const LIST_EXPENSES = 'LIST_EXPENSES';
export const CLEAR_EXPENSES = 'CLEAR_EXPENSES';
export const SHOW_ERROR = 'SHOW_ERROR';

export const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_FAILURE = 'FETCH_RATES_FAILURE';
